version: '3'
services:

    # Z-BlogPHP
    zbp_def:
        container_name: zbp_def
        # build: ./build/zblogphp
        image: wdssmq/zblogphp
        restart: unless-stopped
        ports:
            - "80:80"
        env_file:
            - ./conf/common.env
            - ./conf/site_zbp_def.env
        environment:
            ZC_DB_HOST: MySQL
            ZC_DB_NAME: docker_zbp_def
            ZC_DB_USER: root
            ZC_SKIP_TC_PLUGINS: 1
            TZ: "Asia/Shanghai"
        volumes:
            - ./data/www/zbp_def:/app
            # - ./log/nginx_zbp_def/:/var/log/nginx:rw
            # - ./log/nginx_zbp_def/logs2:/var/lib/nginx/logs:rw
        depends_on:
            - MySQL
        networks:
            - net_web

    # MySQL 5.7
    MySQL:
        container_name: MySQL
        image: mysql/mysql-server:5.7
        restart: unless-stopped
        ports:
            - "3306:3306"
        env_file:
            - ./conf/common.env
        environment:
            MYSQL_ROOT_HOST: 172.%.%.%
            TZ: "Asia/Shanghai"
        volumes:
            - ./data/mysql:/var/lib/mysql:rw
            # - ./log/mysql/:/var/log/mysql/:rw
        networks:
            - net_web

networks:
    net_web:
        external: false

# 执行如下命令后可设置为 external: true
# docker network create -d bridge net_web
