version: '3'
services:

    # Z-BlogPHP
    zbp_def:
        container_name: zbp_def
        # build: ./build
        image: wdssmq/zblogphp
        restart: unless-stopped
        ports:
            - "80:80"
        # env_file:
        #     - ./conf/common.env
        #     - ./conf/site_zbp_def.env
        environment:
            ZC_BLOG_PWDD: ${ZC_BLOG_PWDD_zbp_def:-pwdd_zbp_def}
            ZC_BLOG_USER: ${ZC_BLOG_USER_zbp_def:-admin_zbp_def}
            ZC_DB_HOST: MySQL
            ZC_DB_NAME: docker_zbp_def
            ZC_DB_PWDD: ${MYSQL_ROOT_PASSWORD:-shujukumima1233}
            ZC_DB_USER: root
            ZC_SKIP_TC_PLUGINS: 1
            TZ: "Asia/Shanghai"
        volumes:
            - ./data-www/zbp_def:/app
        depends_on:
            - MySQL
        networks:
            - net_web

    # MySQL 5.7
    MySQL:
        container_name: MySQL
        image: mysql/mysql-server:5.7
        restart: unless-stopped
        ports:
            - "3306:3306"
        # env_file:
        #     - ./conf/common.env
        environment:
            MYSQL_ROOT_HOST: 172.%.%.%
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-shujukumima1233}
            TZ: "Asia/Shanghai"
        volumes:
            - ./data-mysql:/var/lib/mysql:rw
        networks:
            - net_web

networks:
    net_web:
        external: false

# 执行如下命令后可设置为 external: true
# docker network create -d bridge net_web
